<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TrngNi cng tc_school</name>
   <tag></tag>
   <elementGuidId>835a3c74-bfe7-4b4c-9a39-725a3e4b5e64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#school</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='school']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f433e32-36d0-471f-a304-96486bf30964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>school</value>
      <webElementGuid>dcbf481a-8131-4075-bb9d-f2980ecc4c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>school</value>
      <webElementGuid>a39f0064-5070-4320-9a1d-7a22a06e5dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90c96a0e-6786-4854-9630-20766f301bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;school&quot;)</value>
      <webElementGuid>6af3c18b-a303-446b-9f2a-3e3184b1d5d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='school']</value>
      <webElementGuid>95d33bf5-f7ef-4631-9ba2-68049f4e61f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='post-register-form']/div[3]/input</value>
      <webElementGuid>84b2ac24-dfce-49c5-858f-f1a110dfbe97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>404edd5c-c9b3-4f47-8875-086cb6456ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'school' and @name = 'school' and @type = 'text']</value>
      <webElementGuid>8c1c6e8e-842e-44d0-976b-b822f11a3e15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
