<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ng s 3, Linh ng, Th c, Thnh ph H Ch Minh</name>
   <tag></tag>
   <elementGuidId>3d1180fd-90c8-455f-8cbe-b59dbe652098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b8f68098-53c8-4858-97bb-a11a64825acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>70015251-99b1-4f9d-a772-60cb4b32039f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>4ddd9dc8-44f8-4c59-9208-bc88666ff939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1612c371-6d12-4c8b-a1e6-403b91e2016d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100</value>
      <webElementGuid>f06f1300-9c6d-48a3-adfd-832753623e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đường số 3, Linh Đông, Thủ Đức, Thành phố Hồ Chí Minh</value>
      <webElementGuid>34df1e9f-ef70-4f0e-be06-ef3cac743a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address&quot;)</value>
      <webElementGuid>3ab4ca79-69bd-48c4-b9dc-bc835ec08ca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='address']</value>
      <webElementGuid>7a28e347-d3c3-45b5-b3be-9a2b2c558b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ:'])[1]/following::textarea[1]</value>
      <webElementGuid>8f451a38-b8ea-495f-a8f9-20f7d340fcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theo dự án'])[1]/following::textarea[1]</value>
      <webElementGuid>a75dc2b0-9bad-4584-b9c0-0eb3d598ee4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vị trí:'])[1]/preceding::textarea[1]</value>
      <webElementGuid>98bfd2dc-3a81-4c87-bc6f-040b7f2496cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thủ Đức'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a1f4f42b-2c65-44a9-a66b-144ba04d76d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đường số 3, Linh Đông, Thủ Đức, Thành phố Hồ Chí Minh']/parent::*</value>
      <webElementGuid>6bc9ed8e-0b54-4e61-a028-f8a6144089fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/h3/textarea</value>
      <webElementGuid>6d5317ba-6a79-4184-af43-3a3353e8312b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'address' and @name = 'address' and (text() = 'Đường số 3, Linh Đông, Thủ Đức, Thành phố Hồ Chí Minh' or . = 'Đường số 3, Linh Đông, Thủ Đức, Thành phố Hồ Chí Minh')]</value>
      <webElementGuid>02780e8d-4146-49bb-8cbf-ad88de3e7c44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
