<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Bn tri cy ti ch Th c t th 2 n th 6_ac92c3</name>
   <tag></tag>
   <elementGuidId>93c859a1-c73c-43ae-88c6-4858cc0b807b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>83d92a76-721f-400b-8ae9-ef7cf9e49cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>f2f87078-1f2f-4bbb-b655-eb23a83b7e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>c61c6187-e440-45a1-8426-92fa4895b37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>92bc8c5d-2fbf-4cb3-9f4a-e48b6e9305a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100</value>
      <webElementGuid>f4c6dc0d-0736-4b65-8b0a-44941ca1b349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bán trái cây tại chợ Thủ Đức từ thứ 2 đến thứ 6 hằng tuần từ 7:00 đến 16:00</value>
      <webElementGuid>b2cb80b5-7cae-4467-a6e5-827b51b30bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description&quot;)</value>
      <webElementGuid>f6b33f76-a907-4825-bb72-45a8aefd19da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='description']</value>
      <webElementGuid>87150a9e-5219-4842-af60-c581040dfc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô tả:'])[1]/following::textarea[1]</value>
      <webElementGuid>c47c09a8-3118-47e6-b47f-e84e79582dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tên công việc:'])[1]/following::textarea[1]</value>
      <webElementGuid>4e880268-c622-41dd-a761-9b4da08d0fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lương:'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d0c17e8a-d0f4-4168-adac-9a0b111c0e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bán trái cây tại chợ Thủ Đức từ thứ 2 đến thứ 6 hằng tuần từ 7:00 đến 16:00']/parent::*</value>
      <webElementGuid>773525de-1c26-4d19-9de4-e352c8cbaa41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>19070914-fd02-4eb1-a215-d6ce3ad05a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'description' and @name = 'description' and (text() = 'Bán trái cây tại chợ Thủ Đức từ thứ 2 đến thứ 6 hằng tuần từ 7:00 đến 16:00' or . = 'Bán trái cây tại chợ Thủ Đức từ thứ 2 đến thứ 6 hằng tuần từ 7:00 đến 16:00')]</value>
      <webElementGuid>7e910eae-d14c-49a9-8ea9-c04a9eab4637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
