name: katalon-automate

on:
  workflow_run:
    workflows: ['heroku-deploy']
    types:
      - completed
jobs:
  katalon-automate:
    name: Katalon Automate
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run test suite
        uses: katalon-studio/katalon-studio-github-action@v3.0
        with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType="Chrome" -testSuitePath="Test Suites/Basic Test Suite" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
  send-mail:
    name: Send Mails
    runs-on: ubuntu-latest
    needs: [katalon-automate]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Katalon Automate Error
          to: 19120272@student.hcmus.edu.vn, siliem422001@gmail.com
          from: CICD-Demo
          body: Run ${{github.repository}} failed.
